name: CI Testiranje Radix Sort

# Skripta se sproži ob vsakem  pushu na main
on:
  push:
    branches: [ "main" ]

jobs:
  # PRVI POSEL: Preverja obstoj testnih skript
  preverjanje_datotek:
    runs-on: self-hosted # Uporabljam moj laptop kot runner
    steps:
      - name: Pridobivanje kode iz repozitorija
        uses: actions/checkout@v4

      # ZAHTEVA: Preusmeritev standardne napake v datoteko napaka.txt
      # ls skuša najti mapo testi, če je ni, se napaka zapiše v datoteko
      # || true prepreči, da bi se workflow tu ustavil, ker moramo napako prenesti v naslednji posel.
      - name: Preveri če obstaja mapa s testi
        run: ls ./testi > napaka.txt 2>&1 || true

      # ZAHTEVA: Komunikacija med posli preko artefaktov
      - name: Shrani datoteko z napako kot artefakt
        uses: actions/upload-artifact@v4
        with:
          name: statusni-artefakt
          path: napaka.txt

  # DRUGI POSEL: Izvedba testov (odvisen od prvega posla)
  izvedba_testov:
    needs: preverjanje_datotek # ZAHTEVA: Drugi posel je odvisen od prvega
    runs-on: self-hosted
    
    # ZAHTEVA: Obvezna uporaba matrike matrix
    strategy:
      matrix:
        # Simuliramo testiranje na dveh različnih okoljih (razvojno in produkcijsko)
        okolje: [razvoj, produkcija]

    steps:
      - name: Pridobivanje kode
        uses: actions/checkout@v4

      # ZAHTEVA: Prenos artefakta iz prvega posla
      - name: Prenesi artefakt iz prvega posla
        uses: actions/download-artifact@v4
        with:
          name: statusni-artefakt

      # ZAHTEVA: Preverjanje vsebine datoteke napaka.txt
      - name: Preveri vsebino napake in izvedi teste
        run: |
          echo "Preverjam okolje: ${{ matrix.okolje }}"
          if grep -q "ls:" napaka.txt; then
            echo "NAPAKA: Mapa s testi ni bila najdena! Prekinjam..."
            exit 1
          else
            echo "Vse je v redu. Zaganjam teste v okolju ${{ matrix.okolje }}..."
            
            # TA DEL JE KLJUČEN: Odstrani Windows končaje vrstic neposredno na runnerju
            sed -i 's/\r$//' ./testi/run_tests.sh
            
            # Nastavimo pravice in zaženemo
            chmod +x ./testi/run_tests.sh
            ./testi/run_tests.sh
          fi
